apiVersion: v1
kind: Pod
metadata:
  name: my-pod-nginx
  labels:
    app: nginx
  annotations:
    ecrimage: https://aws.com

spec:
  containers:
    - name: my-nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
